name: Deploy Chatbot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build and Deploy Chatbot to Cloud Run
        run: |
          gcloud builds submit chatbot --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/chatbot
          gcloud run deploy chatbot --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/chatbot --region ${{ secrets.GCP_REGION }} --platform managed --allow-unauthenticated
