name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies for chatbot
      run: |
        pip install -r chatbot/requirements.txt
    - name: Install dependencies for ingestion
      run: |
        pip install -r ingestion/requirements.txt
    - name: Install pytest
      run: |
        pip install pytest
    - name: Run chatbot tests
      run: |
        pytest tests/test_chatbot.py --disable-warnings -q
    - name: Run ingestion tests
      if: ${{ !cancelled() }}
      run: |
        pytest tests/test_ingestion.py --disable-warnings -q
